[package]
name = "svico"
version = "0.3.5"
edition = "2024"
description = "🖼️ SVG to Tiny Lossless ICO Converter"
authors = ["kh4f"]
license = "MIT"
repository = "https://github.com/kh4f/svico"
homepage = "https://github.com/kh4f/svico"
documentation = "https://docs.rs/svico"
readme = "README.md"
keywords = ["ico", "favicon", "svg-to-ico", "ico-generator"]
categories = ["command-line-utilities", "graphics"]
include = ["src", "LICENSE"]

[dependencies]
anyhow = "1"
resvg = "0.48"
png = "0.18"
oxipng = { version = "10", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
