[package]
name = "svico"
version = "0.3.2"
edition = "2024"
description = "🖼️ SVG to Tiny Lossless ICO Converter"
authors = ["kh4f"]
license = "MIT"
repository = "https://github.com/kh4f/svico"
readme = "README.md"
keywords = ["svg", "ico", "svg-to-ico", "converter"]
categories = ["command-line-utilities", "graphics"]
include = ["src", "LICENSE"]

[dependencies]
anyhow = "1"
resvg = "0.48"
png = "0.18"
oxipng = "10"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
